spring:
  application:
    name: mall-monitor
  profiles:
    active: dev
  security: # Configure login username and password
    user:
      name: macro
      password: 123456
  boot:  # Do not display admin-server monitoring information
    admin:
      discovery:
        ignored-services: ${spring.application.name}
server:
  port: 8101
