aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # OSS external service access domain name
    accessKeyId: test # User identifier used in access authentication
    accessKeySecret: test # Key used by the user to encrypt signature strings and by OSS to verify signature strings
    bucketName: macro-oss # OSS storage bucket
    policy:
      expire: 300 # Signature validity period (S)
    maxSize: 10 # Uploaded file size (M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # Callback address after successful file upload
    dir:
      prefix: mall/images/ # Uploaded folder path prefix
spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: reader
    password: 123456
  data:
    redis:
      host: redis # Redis server address
      database: 0 # Redis database index (default is 0)
      port: 6379 # Redis server connection port
      password: # No password
minio:
  endpoint: http://192.168.3.101:9090 # MinIO service address
  bucketName: mall # Storage bucket name
  accessKey: minioadmin # Access key
  secretKey: minioadmin # Secret key
logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info
logstash:
  host: logstash