spring:
  data:
    redis:
      host: redis # Redis server address
      database: 0 # Redis database index (default is 0)
      port: 6379 # Redis server connection port
      password: # No password
logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info
logstash:
  host: logstash