spring:
  data:
    redis:
      host: localhost # Redis server address
      database: 0 # Redis database index (default is 0)
      port: 6379 # Redis server connection port
      password: # Redis server connection password (default is empty)
      timeout: 3000ms # Connection timeout (ms)
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost