server:
  port: 8201
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #use lowercase service-id
      routes: #configure route paths
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/mall-auth/**
          filters:
            - StripPrefix=1
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/mall-admin/**
          filters:
            - StripPrefix=1
        - id: mall-portal
          uri: lb://mall-portal
          predicates:
            - Path=/mall-portal/**
          filters:
            - StripPrefix=1
        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/mall-search/**
          filters:
            - StripPrefix=1
        - id: mall-demo
          uri: lb://mall-demo
          predicates:
            - Path=/mall-demo/**
          filters:
            - StripPrefix=1
  data:
    redis:
      database: 0
      port: 6379
      host: redis
      password:
secure:
  ignore:
    urls: #configure whitelist paths
      - "/doc.html"
      - "/v3/api-docs/swagger-config"
      - "/*/v3/api-docs/default"
      - "/*/v3/api-docs"
      - "/*/swagger-ui/**"
      - "/webjars/**"
      - "/favicon.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/mall-auth/**"
      - "/mall-search/**"
      - "/mall-portal/sso/login"
      - "/mall-portal/sso/register"
      - "/mall-portal/sso/getAuthCode"
      - "/mall-portal/home/**"
      - "/mall-portal/product/**"
      - "/mall-portal/brand/**"
      - "/mall-portal/alipay/**"
      - "/mall-admin/admin/login"
      - "/mall-admin/admin/register"
      - "/mall-admin/minio/upload"
management:
  endpoints:
    web:
      exposure:
        include: '*' #expose Actuator monitoring endpoints
  endpoint:
    health:
      show-details: always #show detailed health information
    env:
      show-values: always #by default Actuator environment variables are shown as ****, here enable show
    configprops:
      show-values: always #by default Actuator config properties are shown as ****, here enable show
    info:
      enabled: true
knife4j:
  gateway:
    enabled: true
    strategy: discover #gateway docs aggregation method: service discovery (auto aggregate)
    discover:
      version: openapi3 #configure OpenAPI3 specification
      enabled: true #enable service discovery
      excluded-services: mall-monitor #exclude monitor service
    tags-sorter: order #configure tag sort rule
    operations-sorter: order #configure operation sort rule
sa-token:
  # token name (also cookie name)
  token-name: Authorization
  # token validity period in seconds, -1 means never expires
  timeout: 2592000
  # token temporary validity period (if no operation within specified time, token expires), unit: seconds
  active-timeout: -1
  # allow concurrent login for same account (if false, new login kicks out old login)
  is-concurrent: true
  # whether to share the same token when multiple logins on the same account (false: every login gets a new token)
  is-share: false
  # token style
  token-style: uuid
  # output operation log
  is-log: false
  # read token from cookie
  is-read-cookie: false
  # read token from header
  is-read-header: true
  # token prefix
  token-prefix: Bearer
  # print banner
  is-print: false

