server:
  port: 8085
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5 # Connection pool initial size
      min-idle: 10 # Minimum idle connections
      max-active: 20 # Maximum connections
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # Do not count these request data
      stat-view-servlet: # Login username and password for accessing monitoring page
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
    redis:
      host: localhost # Redis server address
      database: 0 # Redis database index (default is 0)
      port: 6379 # Redis server connection port
      password:  # Redis server connection password (default is empty)
      timeout: 3000ms # Connection timeout (milliseconds)
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*' # Expose Actuator monitoring endpoints
  endpoint:
    health:
      show-details: always # Show detailed health information
    env:
      show-values: always # By default, Actuator environment variables are displayed as ****, here we enable display
    configprops:
      show-values: always # By default, Actuator configuration properties are displayed as ****, here we enable display
    info:
      enabled: true
redis:
  database: mall-swarm
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # Verification code expiration time
    common: 86400 # 24 hours
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue
springdoc:
  swagger-ui:
    # Modify Swagger UI path
    path: /swagger-ui.html
    # Enable Swagger UI interface
    enabled: true
    # Configure tag and operation expansion method, here configured as no expansion
    doc-expansion: 'none'
  api-docs:
    # Modify api-docs path
    path: /v3/api-docs
    # Enable api-docs
    enabled: true
  group-configs:
    - group: 'mall-portal'
      packages-to-scan: com.macro.mall.portal.controller
sa-token:
  # Token name (also cookie name)
  token-name: Authorization
  # Token validity period, unit: seconds, -1 means never expires
  timeout: 604800
  # Token temporary validity period (no operation within specified time is considered token expiration), unit: seconds
  active-timeout: -1
  # Whether to allow concurrent login for the same account (when false, new login kicks out old login)
  is-concurrent: true
  # When multiple people log in to the same account, whether to share one token (when false, create a new token for each login)
  is-share: false
  # Token style
  token-style: uuid
  # Whether to output operation logs
  is-log: false
  # Whether to read token from cookie
  is-read-cookie: false
  # Whether to read token from header
  is-read-header: true
  # Token prefix
  token-prefix: Bearer
  # JWT secret key
  jwt-secret-key: sa-secret-key123
  # Whether to print banner
  is-print: false
