server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5 #connection pool initial size
      min-idle: 10 #minimum idle connections
      max-active: 20 #maximum connections
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #do not count these requested data
      stat-view-servlet: #login username/password for monitoring web page
        login-username: druid
        login-password: druid
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: localhost:9200
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*' #expose Actuator monitoring endpoints
  endpoint:
    health:
      show-details: always #show details of health
    env:
      show-values: always #by default, environment variables are shown as ****, enable here for display
    configprops:
      show-values: always #by default, config properties shown as ****, enable here for display
    info:
      enabled: true
springdoc:
  swagger-ui:
    # Change Swagger UI path
    path: /swagger-ui.html
    # Enable Swagger UI interface
    enabled: true
    # Configure tag and operation expansion (none = not expanded)
    doc-expansion: 'none'
  api-docs:
    # Change api-docs path
    path: /v3/api-docs
    # Enable api-docs
    enabled: true
  group-configs:
    - group: 'mall-search'
      packages-to-scan: com.macro.mall.search.controller



