apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-monitor-deployment
  namespace: default
  labels:
    app: mall-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-monitor
  template:
    metadata:
      labels:
        app: mall-monitor
    spec:
      containers:
        - name: mall-monitor
          image: mall/mall-monitor:1.0-SNAPSHOT
          ports:
            - containerPort: 8101
          env:
            # Specify environment
            - name: spring.profiles.active
              value: prod
            # Specify timezone
            - name: TZ
              value: Asia/Shanghai
            # Specify Nacos address
            - name: spring.cloud.nacos.discovery.server-addr
              value: http://192.168.3.101:8848
            - name: spring.cloud.nacos.config.server-addr
              value: http://192.168.3.101:8848
          volumeMounts:
            - mountPath: /var/logs
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /mydata/app/mall-monitor/logs
            type: DirectoryOrCreate